name: 'Setup Composite Action'
description: 'Setup Node.js and pnpm'
runs:
  using: "composite"
  steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Read .nvmrc file
        shell: bash
        id: nvmrc
        run: |
          if [ -f .nvmrc ]; then
            echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
          else
            echo "::error::File .nvmrc not found!"
            exit 1
          fi

      - name: Set up Node.js
        shell: bash
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        shell: bash
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        shell: bash
        run: pnpm install