name = "founder-swap-orange-meets-workers"
compatibility_date = "2024-10-07"
main = "./build/index.js"
compatibility_flags = ["nodejs_compat"]

[vars]
CALLS_APP_ID = ""
TURN_SERVICE_ID = ""
CALLS_APP_SECRET = ""

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]
