name: Block Merge into Main from Non-Release Branches

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Source Branch Name
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" =~ ^release/ ]]; then
            echo "The branch follows the release/* pattern, merge allowed."
          else
            echo "Merge blocked: The branch '${{ github.head_ref }}' does not follow the release/* pattern."
            exit 1
          fi
