name: Check PR Branch Prefix
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-branch-prefix:
    runs-on: ubuntu-latest
    steps:
      - name: Check if target branch is master/main
        if: github.base_ref != 'master' && github.base_ref != 'main'
        run: |
          echo "This check is only for PRs targeting 'master' or 'main'. Skipping..."
          exit 0

      - name: Check if source branch starts with release/
        if: github.base_ref == 'master' || github.base_ref == 'main'
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^release/ ]]; then
            echo "::error::Branch name '${{ github.head_ref }}' does not start with 'release/'. Only branches with the prefix 'release/' are allowed for PRs targeting 'master' or 'main'."
            exit 1
          fi