name: Automated Release for Single App

on:
  push:
    branches:
      - main

jobs:
  release:
   
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-composite-action

      - name: Use pnpm from setup
        run: pnpm --version
        
      # 🔹 Determine type of versione (patch/minor/major) from PR title
      - name: Determine version type from PR title
        if: github.event_name == 'pull_request'
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" == *"#minor"* ]]; then
            VERSION_TYPE="minor"
          elif [[ "$PR_TITLE" == *"#major"* ]]; then
            VERSION_TYPE="major"
          else
            VERSION_TYPE="patch"
          fi
          echo "VERSION_TYPE=$VERSION_TYPE" >> $GITHUB_ENV
          
      - name: Increment version only if needed
        run: |
          cd apps/web  # ✅ APP PATH

          # check package.json has version, otherwise add it
          if ! jq -e '.version' package.json > /dev/null; then
            echo "No version found in package.json. Setting default version to 1.0.0."
            jq '. + {version: "1.0.0"}' package.json > tmp.json && mv tmp.json package.json
          fi

          CURRENT_VERSION=$(jq -r .version package.json)
          NEW_VERSION=$(pnpm pkg version $VERSION_TYPE --no-git-tag-version | sed 's/"//g')

          if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
            echo "No version change needed for web"
            exit 0
          fi

          echo "New version for web: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          # Back to project root
          cd ../../
          
          # Add modified files
          git add .
          git commit -m "chore: bump web to $NEW_VERSION"

      - name: Create and push release branch
        if: env.NEW_VERSION != ''
        run: |
          
          # Remove prefix "v" from version if exists
          CLEAN_VERSION=$(echo "${{ env.NEW_VERSION }}" | sed 's/^v//')
          RELEASE_BRANCH="release/v$CLEAN_VERSION"

          echo "Creating release branch: $RELEASE_BRANCH"
          git checkout -b $RELEASE_BRANCH
          git push origin $RELEASE_BRANCH

      - name: Create and push tag
        if: env.NEW_VERSION != ''
        run: |
          cd apps/web
          TAG_NAME="web-v${{ env.NEW_VERSION }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        if: env.NEW_VERSION != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "web-v${{ env.NEW_VERSION }}"
          name: "Release web ${{ env.NEW_VERSION }}"
          body: "Automated release for `web` version `${{ env.NEW_VERSION }}`"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push next release branch
        if: env.NEW_VERSION != ''
        run: |
          cd apps/web
          NEXT_VERSION=$(pnpm version patch --no-git-tag-version | tail -n 1)
          NEXT_BRANCH="release/v$NEXT_VERSION"
          
          echo "Creating next release branch: $NEXT_BRANCH"
          
          git checkout -b $NEXT_BRANCH
          git push origin $NEXT_BRANCH
