name: Automated Release for Single App

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-composite-action

      - name: Use pnpm from setup
        run: pnpm --version
        
      # 🔹 Determine type of version (patch/minor/major) from PR title
      - name: Determine version type from PR title
        if: github.event_name == 'pull_request'
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" == *"#minor"* ]]; then
            VERSION_TYPE="minor"
          elif [[ "$PR_TITLE" == *"#major"* ]]; then
            VERSION_TYPE="major"
          else
            VERSION_TYPE="patch"
          fi
          echo "VERSION_TYPE=$VERSION_TYPE" >> $GITHUB_ENV
          
      
      - name: Increment version manually
        run: |
          # Leggi la versione corrente dal package.json
          CURRENT_VERSION=$(cat apps/web/package.json | grep '"version":' | awk -F'"' '{print $4}')
          echo "Current version: $CURRENT_VERSION"

          # Incrementa la versione (patch)
          NEW_VERSION=$(echo "$CURRENT_VERSION" | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "New version: $NEW_VERSION"

          # Aggiorna il file package.json con la nuova versione
          sed -i "s/\"version\": \"$CURRENT_VERSION\"/\"version\": \"$NEW_VERSION\"/" apps/web/package.json

          # Stampa la nuova versione per debug
          echo "Updated version to: $NEW_VERSION"

          # Salva la nuova versione in una variabile di ambiente per i passaggi successivi
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV



      - name: Debug NEW_VERSION
        run: |
          echo "NEW_VERSION is set to: ${{ env.NEW_VERSION }}"
          echo "Current directory: $(pwd)"

      - name: Create and push release branch
        if: env.NEW_VERSION != '' && env.NEW_VERSION != 'None'
        run: |
          # Remove prefix "v" from version if exists
          CLEAN_VERSION=$(echo "${{ env.NEW_VERSION }}" | sed 's/^v//')
          RELEASE_BRANCH="release/v$CLEAN_VERSION"

          echo "Creating release branch: $RELEASE_BRANCH"
          git checkout -b $RELEASE_BRANCH
          git push origin $RELEASE_BRANCH

      - name: Create and push tag
        if: env.NEW_VERSION != ''
        run: |
          TAG_NAME="web-v${{ env.NEW_VERSION }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        if: env.NEW_VERSION != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "web-v${{ env.NEW_VERSION }}"
          name: "Release web ${{ env.NEW_VERSION }}"
          body: "Automated release for `web` version `${{ env.NEW_VERSION }}`"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push next release branch
        if: env.NEW_VERSION != ''
        run: |
          NEXT_VERSION=$(pnpm -C apps/web version patch --no-git-tag-version | tail -n 1)
          NEXT_BRANCH="release/v$NEXT_VERSION"
          
          echo "Creating next release branch: $NEXT_BRANCH"
          
          git checkout -b $NEXT_BRANCH
          git push origin $NEXT_BRANCH