name: Setup Node.js and pnpm

on:
  workflow_call:
    outputs:
      node_version:
        description: "Node.js version from .nvmrc"
        value: ${{ jobs.setup.outputs.node_version }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.nvmrc.outputs.node_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read .nvmrc file
        id: nvmrc
        run: |
          if [ -f .nvmrc ]; then
            echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
            echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
          else
            echo "::error::File .nvmrc not found!"
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm using npx
        run: npx pnpm@8 --version

      - name: Verify pnpm installation
        run: npx pnpm@8 --version

      - name: Install dependencies
        run: npx pnpm@8 install
