name: Apply Supabase Migrations

on:
  pull_request:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:

      - name: Setup environment
        uses: ./.github/actions/setup-composite-action

      - name: Use pnpm from setup
        run: pnpm --version

      - name: Install Supabase CLI
        run: pnpm add -g supabase

      - name: Authenticate with Supabase
        run: supabase login --token $SUPABASE_TOKEN
        env:
          SUPABASE_TOKEN: ${{ secrets.SUPABASE_TOKEN }}

      - name: Link Supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_REF_PROD
        env:
          SUPABASE_PROJECT_REF_PROD: ${{ secrets.SUPABASE_PROJECT_REF_PROD }}

      - name: Apply Supabase migrations
        run: supabase db push --password $SUPABASE_DB_PASSWORD_PROD
        env:
          SUPABASE_DB_PASSWORD_PROD: ${{ secrets.SUPABASE_DB_PASSWORD_PROD }}
